/**
 * Global setup for the minikube-live suite.
 *
 * Stands up a fully helm-deployed kubeclaw release in minikube, pointed at the
 * real LLM provider at LIVE_LLM_BASE_URL. Runs in its own namespace
 * (`kubeclaw-live`) so it does not collide with any existing `kubeclaw`
 * install used by the regular e2e suite.
 *
 * Provider config (override via env vars):
 *   LIVE_LLM_BASE_URL   http://localhost:11434/v1  (default — set to override)
 *   LIVE_LLM_MODEL      gemma-4-E4B-it-Q4_0.gguf
 *   LIVE_LLM_API_KEY    no-key
 *
 * Channel pod auth (the deployed HTTP channel uses Basic auth):
 *   USER  = alice
 *   PASS  = livepass
 *
 * Test driver port-forwards svc/kubeclaw-channel-http →
 * localhost:KUBECLAW_LIVE_HTTP_LOCAL_PORT.
 */
import { spawn, spawnSync, type ChildProcess } from 'child_process';
import { readdirSync, statSync } from 'fs';
import { join } from 'path';
import { installCertManager } from '../setup/cert-manager.js';
import { LIVE_BASE_URL, LIVE_MODEL, LIVE_API_KEY } from './lib/live-llm.js';

const NAMESPACE = 'kubeclaw-live';
const RELEASE = 'kubeclaw-live';
const CHART_DIR = './helm/kubeclaw';

export const KUBECLAW_LIVE_HTTP_LOCAL_PORT = 14081;
export const KUBECLAW_LIVE_REDIS_LOCAL_PORT = 16381;
// Primary user (kept for backward compatibility with existing test files).
export const KUBECLAW_LIVE_USER = 'alice';
export const KUBECLAW_LIVE_PASS = 'livepass';
// Named aliases used by the multi-user isolation suite.
export const KUBECLAW_LIVE_USER_A = 'alice';
export const KUBECLAW_LIVE_PASS_A = 'livepass';
export const KUBECLAW_LIVE_USER_B = 'bob';
export const KUBECLAW_LIVE_PASS_B = 'bobpass';

// ── oauth-webchat channel constants ──────────────────────────────────────────
// Port 14082 — non-clashing with HTTP (14081) and Redis (16381).
// The test user alice@test.local is hardcoded in the test-oauth-provider fixture.
export const KUBECLAW_LIVE_OAUTH_WEBCHAT_LOCAL_PORT = 14082;

// ── admin shell constants ─────────────────────────────────────────────────────
// Port 14083 — next free after oauth-webchat (14082).
// The orchestrator's admin sidecar listens on port 9090 cluster-internal.
// The admin password is auto-generated by the chart and stored in kubeclaw-secrets.
export const KUBECLAW_LIVE_ADMIN_LOCAL_PORT = 14083;
export const KUBECLAW_LIVE_ADMIN_USERNAME = 'admin';
// Initialised inside setup() by reading the chart-managed Secret.
export let KUBECLAW_LIVE_ADMIN_PASS = '';
// Port 18090 — local port-forward for the in-cluster test OIDC provider.
// Tests use this to follow the authorize redirect from the host.
export const KUBECLAW_LIVE_TEST_OAUTH_LOCAL_PORT = 18090;
export const KUBECLAW_LIVE_OAUTH_WEBCHAT_USER = 'alice@test.local';
// Cookie secret must be ≥32 chars (enforced by parseConfig).
export const KUBECLAW_LIVE_OAUTH_WEBCHAT_COOKIE_SECRET =
  'kubeclaw-live-e2e-oauth-cookie-secret-32bytes!';

// Read from a Secret at runtime (initialised inside setup()).
export let KUBECLAW_LIVE_REDIS_URL = '';

let portForwardProcess: ChildProcess | null = null;
let redisPortForwardProcess: ChildProcess | null = null;
let oauthWebchatPortForwardProcess: ChildProcess | null = null;
let testOauthPortForwardProcess: ChildProcess | null = null;
let adminPortForwardProcess: ChildProcess | null = null;

function sleep(ms: number) {
  return new Promise<void>((r) => setTimeout(r, ms));
}

function run(
  cmd: string,
  args: string[],
  opts: { timeout?: number; allowFail?: boolean } = {},
): { ok: boolean; stdout: string; stderr: string } {
  const result = spawnSync(cmd, args, {
    encoding: 'utf8',
    stdio: 'pipe',
    timeout: opts.timeout ?? 60_000,
  });
  if (result.status !== 0 && !opts.allowFail) {
    throw new Error(
      `[${cmd} ${args.join(' ')}] exit ${result.status}\nstderr: ${result.stderr}\nstdout: ${result.stdout}`,
    );
  }
  return {
    ok: result.status === 0,
    stdout: result.stdout ?? '',
    stderr: result.stderr ?? '',
  };
}

// CNI required for NetworkPolicy enforcement. The live suite's
// minikube-live-network-policy tests assume Cilium (or another enforcing CNI)
// is installed; minikube's default bridge CNI silently ignores
// NetworkPolicies, which lets policy regressions ship without a test signal.
const REQUIRED_CNI = 'cilium';

function isEnforcingCniReady(): boolean {
  // Detect by checking for a Cilium DaemonSet in kube-system.
  const r = spawnSync(
    'kubectl',
    [
      'get',
      'daemonset',
      'cilium',
      '-n',
      'kube-system',
      '-o',
      'jsonpath={.status.numberReady}',
    ],
    { encoding: 'utf8' },
  );
  if (r.status !== 0) return false;
  const ready = parseInt(r.stdout.trim() || '0', 10);
  return ready > 0;
}

async function ensureMinikube(): Promise<void> {
  const which = run('which', ['minikube'], { allowFail: true });
  if (!which.ok) {
    throw new Error(
      'minikube is not installed and the live suite requires it for CNI control.',
    );
  }

  // Probe current minikube status. If running with the wrong CNI, recreate.
  const status = run('minikube', ['status', '--format={{.Host}}'], {
    allowFail: true,
  });
  const isRunning = status.ok && status.stdout.trim() === 'Running';

  if (isRunning && isEnforcingCniReady()) {
    console.log(`✅ minikube running with ${REQUIRED_CNI} CNI`);
    return;
  }

  if (isRunning) {
    console.log(
      `⚠️  minikube is running but ${REQUIRED_CNI} DaemonSet is not present — ` +
        'recreating cluster so NetworkPolicy enforcement is active.',
    );
    const del = run('minikube', ['delete'], {
      timeout: 120_000,
      allowFail: true,
    });
    if (!del.ok) {
      console.warn(
        '⚠️  minikube delete reported non-zero; continuing to start anyway.',
      );
    }
  }

  console.log(`🚀 Starting minikube with --cni=${REQUIRED_CNI}...`);
  // 8 GB / 4 CPU — the live-suite now installs ~6 capabilities at runtime
  // across the test files; under 4 GB/2 CPU the orchestrator's task-request
  // queue backs up and downstream test beforeAlls time out waiting for
  // Deployments.
  const start = run(
    'minikube',
    [
      'start',
      '--driver=docker',
      '--memory=8192',
      '--cpus=4',
      `--cni=${REQUIRED_CNI}`,
      '--wait=all',
    ],
    { timeout: 600_000 },
  );
  if (!start.ok) {
    throw new Error('minikube start failed');
  }
  run('kubectl', ['config', 'use-context', 'minikube']);
  run('kubectl', ['cluster-info']);

  console.log(`⏳ Waiting for ${REQUIRED_CNI} DaemonSet to be ready...`);
  const cniDeadline = Date.now() + 180_000;
  while (Date.now() < cniDeadline) {
    if (isEnforcingCniReady()) {
      console.log(`✅ ${REQUIRED_CNI} ready`);
      return;
    }
    await new Promise((r) => setTimeout(r, 3000));
  }
  throw new Error(`${REQUIRED_CNI} DaemonSet did not become Ready within 180s`);
}

function latestMtimeUnder(
  dir: string,
  exclude: Set<string> = new Set(['node_modules', '.git', '.claude', 'dist']),
): number {
  let latest = 0;
  const stack: string[] = [dir];
  while (stack.length) {
    const cur = stack.pop()!;
    let entries: string[];
    try {
      entries = readdirSync(cur);
    } catch {
      continue;
    }
    for (const name of entries) {
      if (exclude.has(name)) continue;
      const p = join(cur, name);
      let st;
      try {
        st = statSync(p);
      } catch {
        continue;
      }
      if (st.isDirectory()) stack.push(p);
      else if (st.mtimeMs > latest) latest = st.mtimeMs;
    }
  }
  return latest;
}

async function ensureImage(
  imageName: string,
  dockerfile: string,
  contextDir: string = '.',
  requiredFiles: string[] = [],
  sourceDirs: string[] = [],
): Promise<void> {
  console.log(`🐳 Checking for ${imageName} in minikube docker daemon...`);
  const check = spawnSync(
    'bash',
    [
      '-c',
      `eval $(minikube docker-env) && docker image inspect ${imageName} -f "{{.Id}}|{{.Created}}" 2>/dev/null`,
    ],
    { encoding: 'utf8' },
  );

  let needsBuild = !(check.status === 0 && check.stdout.trim());

  // Compare image creation time against the latest mtime under sourceDirs.
  // If any source file is newer, the image is stale and must be rebuilt.
  if (!needsBuild && sourceDirs.length > 0) {
    const created = check.stdout.split('|')[1]?.trim();
    const imageCreatedMs = created ? Date.parse(created) : NaN;
    if (Number.isFinite(imageCreatedMs)) {
      let latest = 0;
      for (const d of sourceDirs) {
        const m = latestMtimeUnder(d);
        if (m > latest) latest = m;
      }
      if (latest > imageCreatedMs) {
        console.log(
          `⚠️  ${imageName} is older than source files in ${sourceDirs.join(', ')} — rebuilding...`,
        );
        needsBuild = true;
      }
    }
  }

  // Even if the image exists, verify required files are present.
  // A stale image built from the wrong Dockerfile may be missing expected
  // artefacts (e.g. tool-server.js) causing tool pods to crash with
  // MODULE_NOT_FOUND at runtime.
  if (!needsBuild && requiredFiles.length > 0) {
    for (const f of requiredFiles) {
      const verify = spawnSync(
        'bash',
        [
          '-c',
          `eval $(minikube docker-env) && docker run --rm --entrypoint="" ${imageName} test -f ${f} 2>/dev/null`,
        ],
        { encoding: 'utf8' },
      );
      if (verify.status !== 0) {
        console.log(
          `⚠️  ${imageName} exists but is missing ${f} — rebuilding...`,
        );
        needsBuild = true;
        break;
      }
    }
  }

  if (!needsBuild) {
    console.log(`✅ ${imageName} already present\n`);
    return;
  }

  console.log(`🔨 Building ${imageName} inside minikube docker daemon...`);
  const build = spawnSync(
    'bash',
    [
      '-c',
      `eval $(minikube docker-env) && docker build -t ${imageName} -f ${dockerfile} ${contextDir}`,
    ],
    { encoding: 'utf8', stdio: 'inherit', timeout: 900_000 },
  );
  if (build.status !== 0) {
    throw new Error(`${imageName} build failed (exit ${build.status})`);
  }
  console.log(`✅ ${imageName} built\n`);
}

function waitForPod(labelSelector: string, timeoutMs: number): Promise<void> {
  return new Promise(async (resolve, reject) => {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
      const res = run(
        'kubectl',
        [
          'get',
          'pods',
          '-n',
          NAMESPACE,
          '-l',
          labelSelector,
          '-o',
          'jsonpath={.items[*].status.conditions[?(@.type=="Ready")].status}',
        ],
        { allowFail: true },
      );
      if (
        res.ok &&
        res.stdout
          .trim()
          .split(/\s+/)
          .every((s) => s === 'True')
      ) {
        return resolve();
      }
      await sleep(3000);
    }
    // Dump pod state for debugging
    const dump = run(
      'kubectl',
      ['get', 'pods', '-n', NAMESPACE, '-l', labelSelector, '-o', 'wide'],
      { allowFail: true },
    );
    reject(
      new Error(
        `pods matching ${labelSelector} not Ready within ${timeoutMs}ms\n${dump.stdout}\n${dump.stderr}`,
      ),
    );
  });
}

/**
 * Given the raw stdout of `kubectl get pvc -n <ns> -o json`, return the names
 * of PVCs that are in Terminating state (i.e. have a non-empty deletionTimestamp).
 *
 * This is a pure, side-effect-free function exported for unit testing.
 * Returns [] on any parse error — never throws.
 */
export function stuckTerminatingPvcNames(pvcListJson: string): string[] {
  try {
    if (!pvcListJson || !pvcListJson.trim()) return [];
    const list = JSON.parse(pvcListJson) as {
      items?: Array<{
        metadata?: { name?: string; deletionTimestamp?: string | null };
      }>;
    };
    if (!Array.isArray(list?.items)) return [];
    const names: string[] = [];
    for (const item of list.items) {
      const ts = item?.metadata?.deletionTimestamp;
      if (ts != null && ts !== '') {
        const name = item?.metadata?.name;
        if (name) names.push(name);
      }
    }
    return names;
  } catch {
    return [];
  }
}

/**
 * Pre-install guard: forcibly remove any PVCs in the Terminating state before
 * helm upgrade --install runs.
 *
 * WHY THIS IS NEEDED:
 * When a prior run left the namespace behind (e.g. KUBECLAW_LIVE_KEEP=1, or a
 * teardown that only ran `helm uninstall` without waiting for PVC deletion), its
 * PVCs can remain in Terminating state — the `kubernetes.io/pvc-protection`
 * finalizer prevents deletion until all pods using the PVC are gone. The next
 * run's helm install creates pods that attempt to bind those same-named PVCs,
 * and the scheduler reports:
 *   "0/1 nodes are available: persistentvolumeclaim "kubeclaw-channel-http-sessions"
 *    is being deleted. not found"
 * → the channel-http pod stays Pending forever → globalSetup readiness wait
 * times out (240 s) → the whole suite aborts before a single test runs.
 *
 * Fix: strip the protection finalizer from each stuck PVC so Kubernetes can
 * complete the deletion, then wait (up to 30 s per PVC) for them to disappear.
 * No-op on a clean namespace or if the namespace does not exist yet.
 */
function clearStuckPvcs(): void {
  // List PVCs; if namespace absent or any error, there is nothing to do.
  const result = run('kubectl', ['get', 'pvc', '-n', NAMESPACE, '-o', 'json'], {
    allowFail: true,
  });
  if (!result.ok) return;

  const stuck = stuckTerminatingPvcNames(result.stdout);
  if (stuck.length === 0) return;

  console.log(`🧹 Clearing ${stuck.length} stuck Terminating PVC(s): ${stuck.join(', ')}`);

  for (const name of stuck) {
    // Strip the kubernetes.io/pvc-protection finalizer so the API server can
    // complete the delete. allowFail: the PVC may disappear between list and patch.
    run(
      'kubectl',
      [
        'patch',
        '-n',
        NAMESPACE,
        'pvc',
        name,
        '-p',
        '{"metadata":{"finalizers":null}}',
        '--type=merge',
      ],
      { allowFail: true },
    );
  }

  // Wait for each PVC to actually disappear (up to 30 s each).
  for (const name of stuck) {
    run(
      'kubectl',
      [
        'wait',
        '--for=delete',
        `pvc/${name}`,
        '-n',
        NAMESPACE,
        '--timeout=30s',
      ],
      { allowFail: true, timeout: 35_000 },
    );
    console.log(`🧹   PVC ${name} deleted`);
  }
}

async function helmInstall(): Promise<void> {
  // Guard: remove any Terminating PVCs from a prior run before helm creates pods
  // that would try to bind them (which would leave those pods Pending forever).
  clearStuckPvcs();

  // Pre-create the namespace with Helm ownership metadata.
  run('kubectl', ['create', 'namespace', NAMESPACE], { allowFail: true });
  run('kubectl', [
    'label',
    'namespace',
    NAMESPACE,
    'app.kubernetes.io/managed-by=Helm',
    '--overwrite',
  ]);
  run('kubectl', [
    'annotate',
    'namespace',
    NAMESPACE,
    `meta.helm.sh/release-name=${RELEASE}`,
    `meta.helm.sh/release-namespace=${NAMESPACE}`,
    '--overwrite',
  ]);

  // Clean up any prior channel Secret left from a failed run — the chart
  // recreates it from values below.
  run(
    'kubectl',
    [
      'delete',
      'secret',
      'kubeclaw-channel-http',
      '-n',
      NAMESPACE,
      '--ignore-not-found',
    ],
    { allowFail: true },
  );

  console.log(
    `📦 helm install ${RELEASE} → ${NAMESPACE} (LLM=${LIVE_BASE_URL}, model=${LIVE_MODEL})...`,
  );
  const setArgs = [
    'upgrade',
    '--install',
    RELEASE,
    CHART_DIR,
    '--namespace',
    NAMESPACE,
    '-f',
    './helm/kubeclaw/values-minikube.yaml',
    '--timeout',
    '180s',
    '--set',
    `namespace=${NAMESPACE}`,
    '--set',
    `secrets.anthropicApiKey=test-key`,
    '--set',
    `secrets.openaiApiKey=${LIVE_API_KEY}`,
    '--set-string',
    `secrets.openaiBaseUrl=${LIVE_BASE_URL}`,
    '--set-string',
    `secrets.directLlmModel=${LIVE_MODEL}`,
    // Chart auto-creates kubeclaw-channel-http with these users (comma-separated user:pass pairs).
    // Use --set-string to prevent helm from treating the value as a YAML list.
    // Commas in --set-string values must be escaped as \, to prevent list-splitting.
    '--set-string',
    `secrets.httpChannelUsers=${KUBECLAW_LIVE_USER_A}:${KUBECLAW_LIVE_PASS_A}\\,${KUBECLAW_LIVE_USER_B}:${KUBECLAW_LIVE_PASS_B}`,
    '--set',
    `credentialInjection.mode=off`,
    // 8080 = local LLM endpoint, 6333 = Qdrant (RAG), 6667 = test IRC daemon,
    // 3000 = MCP capability pods (channel→capability for tools tests).
    '--set',
    `networkPolicy.extraEgressPorts={8080,6333,6667,3000}`,
    // Note: the test MCP capability is installed at RUNTIME from the test
    // file (via Redis IPC), not at helm time — this avoids a startup-time race
    // where the orchestrator publishes capabilities_update before the channel
    // pod has subscribed to its control channel.
    '--set',
    `channels.http.enabled=true`,
    '--set',
    `channels.http.type=http`,
    '--set',
    `channels.http.httpPort=4080`,
    '--set',
    `channels.http.envVars[0].name=HTTP_CHANNEL_USERS`,
    '--set',
    `channels.http.envVars[0].key=users`,
    '--set',
    `channels.http.envVars[1].name=HTTP_CHANNEL_PORT`,
    '--set',
    `channels.http.envVars[1].key=port`,
    '--set',
    `channels.http.envVars[1].optional=true`,
    // Use the chart's `capabilities:` helm-time templates to deploy our
    // test embedding server as a Deployment+Service at
    // kubeclaw-capability-test-embed:8080 — channel pods reach it by name.
    '--set',
    'capabilities.test-embed.image=kubeclaw-test-embedding:latest',
    '--set',
    'capabilities.test-embed.port=8080',
    // Point the embedding client (in channel pod) at the test embedding
    // server. Also override embedding dim to match the fixture (1536).
    '--set-string',
    `secrets.embeddingBaseUrl=http://kubeclaw-capability-test-embed:8080/v1`,
    '--set',
    'secrets.embeddingDim=1536',
    // Deploy the test IRC daemon as a capability pod. The capability template
    // renders a Deployment+Service named kubeclaw-capability-test-ircd.
    // Port 6667 is the IRC port; the readiness probe targets it via tcpSocket.
    // The HTTP side-channel (8080) is only reached via kubectl exec from tests.
    '--set',
    'capabilities.test-ircd.image=kubeclaw-test-ircd:latest',
    '--set',
    'capabilities.test-ircd.port=6667',
    // Deploy the test OIDC provider as a capability pod. It serves the
    // OpenID Connect Authorization Code flow for the oauth-webchat channel.
    // Port 8080 is already allowed by extraEgressPorts — no additional
    // network-policy change needed. The test user is alice@test.local.
    '--set',
    'capabilities.test-oauth.image=kubeclaw-test-oauth:latest',
    '--set',
    'capabilities.test-oauth.port=8080',
    // Register the Researcher specialist so @Researcher mentions are dispatched
    // to the specialist runner. The default chart values.yaml has specialists:[]
    // (empty); we inject it here so the minikube-live suite gets the specialist
    // without requiring changes to the chart defaults.
    // Used by e2e/minikube-live-researcher.test.ts.
    '--set-json',
    'specialists=[{"name":"Researcher","prompt":"You are a web-research specialist. When given a topic or question:\\n1. Search for relevant, current information using available search tools.\\n2. Fetch and read promising sources to gather details.\\n3. Synthesise findings into a concise, structured summary with:\\n   - A one-paragraph executive summary.\\n   - Key facts as a bulleted list.\\n   - Source URLs cited inline.\\nStay factual; note when information is uncertain or conflicting.\\n","triggers":["researcher"],"llmProvider":"openrouter","tools":["web_search","web_fetch"]}]',
    // Bootstrap http-echo + nanoid-echo manifests + skills — installed at chart-time
    // so the orchestrator's baseline reconciler picks them up at startup.
    // http-echo used by e2e/minikube-live-bootstrap-channel-http-echo.test.ts.
    // nanoid-echo used by e2e/minikube-live-channel-src-push.test.ts.
    '--set-json',
    'bootstrap.channelManifests={"http-echo":{"packageJson":"{\\"name\\":\\"http-echo-runtime\\",\\"version\\":\\"1.0.0\\",\\"dependencies\\":{}}","packageLockJson":"{\\"name\\":\\"http-echo-runtime\\",\\"version\\":\\"1.0.0\\",\\"lockfileVersion\\":3,\\"requires\\":true,\\"packages\\":{\\"\\":{\\"name\\":\\"http-echo-runtime\\",\\"version\\":\\"1.0.0\\"}}}","manifestHash":"edbb5411113738f81dcb0b203fcf41fbc12197bff9a64d80bb0d7641a18a9961"},"nanoid-echo":{"packageJson":"{\\"name\\":\\"nanoid-echo-runtime\\",\\"version\\":\\"1.0.0\\",\\"dependencies\\":{\\"nanoid\\":\\"5.0.7\\"}}","packageLockJson":"{\\"name\\":\\"nanoid-echo-runtime\\",\\"version\\":\\"1.0.0\\",\\"lockfileVersion\\":3,\\"requires\\":true,\\"packages\\":{\\"\\": {\\"name\\":\\"nanoid-echo-runtime\\",\\"version\\":\\"1.0.0\\",\\"dependencies\\":{\\"nanoid\\":\\"5.0.7\\"}},\\"node_modules/nanoid\\":{\\"version\\":\\"5.0.7\\",\\"resolved\\":\\"https://registry.npmjs.org/nanoid/-/nanoid-5.0.7.tgz\\",\\"integrity\\":\\"sha512-oLxFY2gd2IqnjcYyOXD8XGCftpGtZP2AbHbOkthDkvRywH5ayNtPVy9YlOPcHckXzbLTCHpkb7FB+yuxKV13pQ==\\",\\"funding\\":[{\\"type\\":\\"github\\",\\"url\\":\\"https://github.com/sponsors/ai\\"}],\\"license\\":\\"MIT\\",\\"bin\\":{\\"nanoid\\":\\"bin/nanoid.js\\"},\\"engines\\":{\\"node\\":\\"^18 || >=20\\"}}}}","manifestHash":"eed310417fb4b8d830ab79c719aca128293e065601a0bdbf575a1ab05b2962c5"},"irc":{"packageJson":"{\\"name\\":\\"irc-runtime\\",\\"version\\":\\"1.0.0\\",\\"dependencies\\":{\\"irc-upd\\":\\"0.11.0\\"}}","packageLockJson":"{\\"name\\":\\"irc-runtime\\",\\"version\\":\\"1.0.0\\",\\"lockfileVersion\\":3,\\"requires\\":true,\\"packages\\":{\\"\\":{\\"name\\":\\"irc-runtime\\",\\"version\\":\\"1.0.0\\",\\"dependencies\\":{\\"irc-upd\\":\\"0.11.0\\"}},\\"node_modules/chardet\\":{\\"version\\":\\"1.6.0\\",\\"resolved\\":\\"https://registry.npmjs.org/chardet/-/chardet-1.6.0.tgz\\",\\"integrity\\":\\"sha512-+QOTw3otC4+FxdjK9RopGpNOglADbr4WPFi0SonkO99JbpkTPbMxmdm4NenhF5Zs+4gPXLI1+y2uazws5TMe8w==\\",\\"license\\":\\"MIT\\",\\"optional\\":true},\\"node_modules/iconv-lite\\":{\\"version\\":\\"0.6.3\\",\\"resolved\\":\\"https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz\\",\\"integrity\\":\\"sha512-4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==\\",\\"license\\":\\"MIT\\",\\"optional\\":true,\\"dependencies\\":{\\"safer-buffer\\":\\">= 2.1.2 < 3.0.0\\"},\\"engines\\":{\\"node\\":\\">=0.10.0\\"}},\\"node_modules/irc-colors\\":{\\"version\\":\\"1.5.0\\",\\"resolved\\":\\"https://registry.npmjs.org/irc-colors/-/irc-colors-1.5.0.tgz\\",\\"integrity\\":\\"sha512-HtszKchBQTcqw1DC09uD7i7vvMayHGM1OCo6AHt5pkgZEyo99ClhHTMJdf+Ezc9ovuNNxcH89QfyclGthjZJOw==\\",\\"license\\":\\"MIT\\",\\"engines\\":{\\"node\\":\\">=6\\"}},\\"node_modules/irc-upd\\":{\\"version\\":\\"0.11.0\\",\\"resolved\\":\\"https://registry.npmjs.org/irc-upd/-/irc-upd-0.11.0.tgz\\",\\"integrity\\":\\"sha512-A1hV5cUkl5HZsKWRYcszD2Usfz33hB8igSSox8dEmrMyfy8/Ra6T/o4jwzs7jYMZ7ljLquSIWzcvSZHZ/bEAZA==\\",\\"license\\":\\"GPL-3.0\\",\\"dependencies\\":{\\"irc-colors\\":\\"^1.5.0\\"},\\"engines\\":{\\"node\\":\\">=0.10.0\\"},\\"optionalDependencies\\":{\\"chardet\\":\\"^1.2.1\\",\\"iconv-lite\\":\\"^0.6.2\\"}},\\"node_modules/safer-buffer\\":{\\"version\\":\\"2.1.2\\",\\"resolved\\":\\"https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz\\",\\"integrity\\":\\"sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==\\",\\"license\\":\\"MIT\\",\\"optional\\":true}}}","manifestHash":"bb913713e2ca96ca392f3febbb9b5355fa6d0636e3d82f0c0f86d4f44406d652","hostMode":"channel-runner"},"oauth-webchat":{"packageJson":"{\\"name\\":\\"oauth-webchat-runtime\\",\\"version\\":\\"1.0.0\\",\\"dependencies\\":{\\"openid-client\\":\\"5.7.1\\"}}","packageLockJson":"{\\"name\\":\\"oauth-webchat-runtime\\",\\"version\\":\\"1.0.0\\",\\"lockfileVersion\\":3,\\"requires\\":true,\\"packages\\":{\\"\\": {\\"name\\":\\"oauth-webchat-runtime\\",\\"version\\":\\"1.0.0\\",\\"dependencies\\":{\\"openid-client\\":\\"5.7.1\\"}},\\"node_modules/jose\\":{\\"version\\":\\"4.15.9\\",\\"resolved\\":\\"https://registry.npmjs.org/jose/-/jose-4.15.9.tgz\\",\\"integrity\\":\\"sha512-1vUQX+IdDMVPj4k8kOxgUqlcK518yluMuGZwqlr44FS1ppZB/5GWh4rZG89erpOBOJjU/OBsnCVFfapsRz6nEA==\\",\\"license\\":\\"MIT\\",\\"funding\\":{\\"url\\":\\"https://github.com/sponsors/panva\\"}},\\"node_modules/lru-cache\\":{\\"version\\":\\"6.0.0\\",\\"resolved\\":\\"https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz\\",\\"integrity\\":\\"sha512-Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==\\",\\"license\\":\\"ISC\\",\\"dependencies\\":{\\"yallist\\":\\"^4.0.0\\"},\\"engines\\":{\\"node\\":\\">=10\\"}},\\"node_modules/object-hash\\":{\\"version\\":\\"2.2.0\\",\\"resolved\\":\\"https://registry.npmjs.org/object-hash/-/object-hash-2.2.0.tgz\\",\\"integrity\\":\\"sha512-gScRMn0bS5fH+IuwyIFgnh9zBdo4DV+6GhygmWM9HyNJSgS0hScp1f5vjtm7oIIOiT9trXrShAkLFSc2IqKNgw==\\",\\"license\\":\\"MIT\\",\\"engines\\":{\\"node\\":\\">= 6\\"}},\\"node_modules/oidc-token-hash\\":{\\"version\\":\\"5.2.0\\",\\"resolved\\":\\"https://registry.npmjs.org/oidc-token-hash/-/oidc-token-hash-5.2.0.tgz\\",\\"integrity\\":\\"sha512-6gj2m8cJZ+iSW8bm0FXdGF0YhIQbKrfP4yWTNzxc31U6MOjfEmB1rHvlYvxI1B7t7BCi1F2vYTT6YhtQRG4hxw==\\",\\"license\\":\\"MIT\\",\\"engines\\":{\\"node\\":\\"^10.13.0 || >=12.0.0\\"}},\\"node_modules/openid-client\\":{\\"version\\":\\"5.7.1\\",\\"resolved\\":\\"https://registry.npmjs.org/openid-client/-/openid-client-5.7.1.tgz\\",\\"integrity\\":\\"sha512-jDBPgSVfTnkIh71Hg9pRvtJc6wTwqjRkN88+gCFtYWrlP4Yx2Dsrow8uPi3qLr/aeymPF3o2+dS+wOpglK04ew==\\",\\"license\\":\\"MIT\\",\\"dependencies\\":{\\"jose\\":\\"^4.15.9\\",\\"lru-cache\\":\\"^6.0.0\\",\\"object-hash\\":\\"^2.2.0\\",\\"oidc-token-hash\\":\\"^5.0.3\\"},\\"funding\\":{\\"url\\":\\"https://github.com/sponsors/panva\\"}},\\"node_modules/yallist\\":{\\"version\\":\\"4.0.0\\",\\"resolved\\":\\"https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz\\",\\"integrity\\":\\"sha512-3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==\\",\\"license\\":\\"ISC\\"}}}","manifestHash":"23bbf5942ef45bd32ed83d1a46c18b337dd005d402474c90046130183dd40c8b","hostMode":"channel-runner","httpPort":4080}}',
    '--set-file',
    'bootstrap.skills.bootstrap-http-echo=helm/kubeclaw/files/bootstrap-skills/bootstrap-http-echo.md',
    '--set-file',
    'bootstrap.skills.bootstrap-nanoid-echo=helm/kubeclaw/files/bootstrap-skills/bootstrap-nanoid-echo.md',
    '--set-file',
    'bootstrap.skills.bootstrap-irc=helm/kubeclaw/files/bootstrap-skills/bootstrap-irc.md',
    '--set-file',
    'bootstrap.skills.bootstrap-oauth-webchat=helm/kubeclaw/files/bootstrap-skills/bootstrap-oauth-webchat.md',
  ];
  const install = run('helm', setArgs, { timeout: 240_000, allowFail: true });
  if (!install.ok) {
    throw new Error(
      `helm install failed:\nstderr: ${install.stderr}\nstdout: ${install.stdout}`,
    );
  }
  console.log('✅ helm install complete\n');
}

async function startPortForward(): Promise<void> {
  console.log(
    `🔌 Port-forward svc/kubeclaw-channel-http → localhost:${KUBECLAW_LIVE_HTTP_LOCAL_PORT}`,
  );
  // Auto-restart wrapper: `kubectl port-forward` exits cleanly when the
  // underlying TCP connection is reset (e.g. by a transient channel-pod
  // hiccup or idle-timeout). Tests reconnect; we restart the forwarder
  // transparently. sleep 0.1 (was 1s) minimises the unavailable window
  // during which in-flight requests would queue or fail.
  portForwardProcess = spawn(
    'bash',
    [
      '-c',
      `while true; do >&2 echo "[port-forward restart $(date +%T)] http"; kubectl port-forward -n ${NAMESPACE} svc/kubeclaw-channel-http ${KUBECLAW_LIVE_HTTP_LOCAL_PORT}:80 || true; sleep 0.1; done`,
    ],
    { stdio: ['ignore', 'ignore', 'inherit'], detached: true },
  );

  // Wait for the port to accept connections.
  for (let i = 0; i < 15; i++) {
    await sleep(1000);
    const nc = spawnSync(
      'nc',
      ['-z', 'localhost', String(KUBECLAW_LIVE_HTTP_LOCAL_PORT)],
      { stdio: 'pipe' },
    );
    if (nc.status === 0) {
      console.log(
        `✅ Port-forward live on :${KUBECLAW_LIVE_HTTP_LOCAL_PORT}\n`,
      );
      return;
    }
  }
  throw new Error('Port-forward did not come up within 15s');
}

async function startRedisPortForward(): Promise<void> {
  // Look up the Redis admin password from the chart-managed Secret so the
  // test can authenticate as the 'orchestrator' ACL user.
  const pwdLookup = run(
    'kubectl',
    [
      'get',
      'secret',
      '-n',
      NAMESPACE,
      'kubeclaw-redis',
      '-o',
      'jsonpath={.data.admin-password}',
    ],
    { allowFail: true },
  );
  if (!pwdLookup.ok || !pwdLookup.stdout) {
    throw new Error('failed to read kubeclaw-redis admin-password Secret');
  }
  const password = Buffer.from(pwdLookup.stdout, 'base64').toString('utf8');
  KUBECLAW_LIVE_REDIS_URL = `redis://orchestrator:${password}@localhost:${KUBECLAW_LIVE_REDIS_LOCAL_PORT}`;

  console.log(
    `🔌 Port-forward svc/kubeclaw-redis → localhost:${KUBECLAW_LIVE_REDIS_LOCAL_PORT}`,
  );
  // Target the Pod directly (not svc/) so the forward survives Service
  // endpoint changes (e.g. when a rolling restart rotates the ready pod).
  // sleep 0.1 (was 1s) minimises the ECONNREFUSED window for ioredis retries.
  redisPortForwardProcess = spawn(
    'bash',
    [
      '-c',
      `while true; do
        >&2 echo "[port-forward restart $(date +%T)] redis"
        POD=$(kubectl get pod -n ${NAMESPACE} -l app=kubeclaw-redis -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
        if [ -n "$POD" ]; then
          kubectl port-forward -n ${NAMESPACE} "pod/$POD" ${KUBECLAW_LIVE_REDIS_LOCAL_PORT}:6379 || true
        fi
        sleep 0.1
      done`,
    ],
    { stdio: ['ignore', 'ignore', 'inherit'], detached: true },
  );
  for (let i = 0; i < 15; i++) {
    await sleep(1000);
    const nc = spawnSync(
      'nc',
      ['-z', 'localhost', String(KUBECLAW_LIVE_REDIS_LOCAL_PORT)],
      { stdio: 'pipe' },
    );
    if (nc.status === 0) {
      console.log(
        `✅ Redis port-forward live on :${KUBECLAW_LIVE_REDIS_LOCAL_PORT}\n`,
      );
      return;
    }
  }
  throw new Error('Redis port-forward did not come up within 15s');
}

async function startTestOauthPortForward(): Promise<void> {
  console.log(
    `🔌 Port-forward svc/kubeclaw-capability-test-oauth → localhost:${KUBECLAW_LIVE_TEST_OAUTH_LOCAL_PORT}`,
  );
  // Tests need to follow the /authorize redirect from the host machine, so we
  // port-forward the in-cluster OIDC provider. This is read-only; no Secret
  // or credentials are exposed.
  testOauthPortForwardProcess = spawn(
    'bash',
    [
      '-c',
      // The capability Service exposes port 8080 (same as the container port).
      `while true; do >&2 echo "[port-forward restart $(date +%T)] test-oauth"; kubectl port-forward -n ${NAMESPACE} svc/kubeclaw-capability-test-oauth ${KUBECLAW_LIVE_TEST_OAUTH_LOCAL_PORT}:8080 || true; sleep 0.1; done`,
    ],
    { stdio: ['ignore', 'ignore', 'inherit'], detached: true },
  );

  for (let i = 0; i < 15; i++) {
    await sleep(1000);
    const nc = spawnSync(
      'nc',
      ['-z', 'localhost', String(KUBECLAW_LIVE_TEST_OAUTH_LOCAL_PORT)],
      { stdio: 'pipe' },
    );
    if (nc.status === 0) {
      console.log(
        `✅ Port-forward live on :${KUBECLAW_LIVE_TEST_OAUTH_LOCAL_PORT}\n`,
      );
      return;
    }
  }
  throw new Error('test-oauth port-forward did not come up within 15s');
}

async function startOauthWebchatPortForward(): Promise<void> {
  console.log(
    `🔌 Port-forward svc/kubeclaw-channel-oauth-webchat → localhost:${KUBECLAW_LIVE_OAUTH_WEBCHAT_LOCAL_PORT} (fire-and-forget; Service created post-bootstrap)`,
  );
  oauthWebchatPortForwardProcess = spawn(
    'bash',
    [
      '-c',
      `while true; do >&2 echo "[port-forward restart $(date +%T)] oauth-webchat"; kubectl port-forward -n ${NAMESPACE} svc/kubeclaw-channel-oauth-webchat ${KUBECLAW_LIVE_OAUTH_WEBCHAT_LOCAL_PORT}:80 || true; sleep 0.1; done`,
    ],
    { stdio: ['ignore', 'ignore', 'inherit'], detached: true },
  );
  // Do not wait for the port to become connectable — the oauth-webchat Service
  // only exists after the bootstrap e2e registers the channel. The bash wrapper
  // auto-retries every 0.1 s, so it will connect naturally once the Service appears.
}

async function startAdminPortForward(): Promise<void> {
  // Read the auto-generated admin HTTP password from the chart-managed Secret.
  const pwdLookup = run(
    'kubectl',
    [
      'get',
      'secret',
      '-n',
      NAMESPACE,
      'kubeclaw-secrets',
      '-o',
      'jsonpath={.data.admin-http-password}',
    ],
    { allowFail: true },
  );
  if (!pwdLookup.ok || !pwdLookup.stdout) {
    throw new Error('failed to read kubeclaw-secrets admin-http-password');
  }
  KUBECLAW_LIVE_ADMIN_PASS = Buffer.from(pwdLookup.stdout, 'base64').toString(
    'utf8',
  );

  console.log(
    `🔌 Port-forward svc/kubeclaw-admin → localhost:${KUBECLAW_LIVE_ADMIN_LOCAL_PORT}`,
  );
  adminPortForwardProcess = spawn(
    'bash',
    [
      '-c',
      `while true; do >&2 echo "[port-forward restart $(date +%T)] admin"; kubectl port-forward -n ${NAMESPACE} svc/kubeclaw-admin ${KUBECLAW_LIVE_ADMIN_LOCAL_PORT}:9090 || true; sleep 0.1; done`,
    ],
    { stdio: ['ignore', 'ignore', 'inherit'], detached: true },
  );

  for (let i = 0; i < 15; i++) {
    await sleep(1000);
    const nc = spawnSync(
      'nc',
      ['-z', 'localhost', String(KUBECLAW_LIVE_ADMIN_LOCAL_PORT)],
      { stdio: 'pipe' },
    );
    if (nc.status === 0) {
      console.log(
        `✅ Admin port-forward live on :${KUBECLAW_LIVE_ADMIN_LOCAL_PORT}\n`,
      );
      return;
    }
  }
  throw new Error('Admin port-forward did not come up within 15s');
}

/**
 * Exported for tests that restart the channel pod — `kubectl port-forward`
 * dies when its backing pod is deleted, so the test re-runs setup.
 *
 * Kills the entire process group (bash wrapper + kubectl child) rather than
 * just the bash parent, then waits for the OS to release the listen port
 * before starting a new wrapper. Without this, the new kubectl fails with
 * "bind: address already in use" and the loop spins until TIME_WAIT expires.
 */
export async function restartChannelPortForward(): Promise<void> {
  if (portForwardProcess?.pid) {
    try {
      process.kill(-portForwardProcess.pid, 'SIGTERM');
    } catch {
      try {
        portForwardProcess.kill();
      } catch {
        /* ignore */
      }
    }
    portForwardProcess = null;
  }
  // Belt-and-braces: kill any stray kubectl holding the HTTP port.
  spawnSync('bash', [
    '-c',
    `pkill -f 'kubectl port-forward.*${KUBECLAW_LIVE_HTTP_LOCAL_PORT}:80' || true`,
  ]);
  // Give the OS TIME_WAIT to clear the listen socket (typically <1 s).
  await sleep(1000);
  await startPortForward();
}

async function teardownImpl() {
  // Kill the bash wrapper AND its child kubectl process. The wrapper restarts
  // kubectl in a loop, so killing only the wrapper leaves a stray kubectl.
  const killTree = (p: ChildProcess | null) => {
    if (!p?.pid) return;
    try {
      process.kill(-p.pid, 'SIGTERM');
    } catch {
      try {
        p.kill();
      } catch {
        /* ignore */
      }
    }
  };
  killTree(portForwardProcess);
  portForwardProcess = null;
  killTree(redisPortForwardProcess);
  redisPortForwardProcess = null;
  killTree(oauthWebchatPortForwardProcess);
  oauthWebchatPortForwardProcess = null;
  killTree(testOauthPortForwardProcess);
  testOauthPortForwardProcess = null;
  killTree(adminPortForwardProcess);
  adminPortForwardProcess = null;
  // Belt-and-braces: kill any lingering kubectl port-forward that targets our ports.
  spawnSync('bash', [
    '-c',
    `pkill -f 'kubectl port-forward.*${KUBECLAW_LIVE_HTTP_LOCAL_PORT}:80' || true`,
  ]);
  spawnSync('bash', [
    '-c',
    `pkill -f 'kubectl port-forward.*${KUBECLAW_LIVE_OAUTH_WEBCHAT_LOCAL_PORT}:80' || true`,
  ]);
  spawnSync('bash', [
    '-c',
    `pkill -f 'kubectl port-forward.*${KUBECLAW_LIVE_TEST_OAUTH_LOCAL_PORT}:8080' || true`,
  ]);
  spawnSync('bash', [
    '-c',
    `pkill -f 'kubectl port-forward.*${KUBECLAW_LIVE_REDIS_LOCAL_PORT}:6379' || true`,
  ]);
  spawnSync('bash', [
    '-c',
    `pkill -f 'kubectl port-forward.*${KUBECLAW_LIVE_ADMIN_LOCAL_PORT}:9090' || true`,
  ]);

  // Diagnostic escape hatch: KUBECLAW_LIVE_KEEP=1 leaves the namespace and all
  // resources in place so pod logs can be inspected post-run. Remember to
  // `helm uninstall` / `kubectl delete ns kubeclaw-live` manually afterward.
  if (process.env.KUBECLAW_LIVE_KEEP) {
    console.log(
      `⚠️  KUBECLAW_LIVE_KEEP set — leaving namespace ${NAMESPACE} intact for inspection.`,
    );
    return;
  }

  // Always uninstall — this is our own isolated namespace.
  run('helm', ['uninstall', RELEASE, '--namespace', NAMESPACE], {
    allowFail: true,
  });
  run(
    'kubectl',
    ['delete', 'namespace', NAMESPACE, '--ignore-not-found', '--timeout=60s'],
    { allowFail: true, timeout: 90_000 },
  );
}

// Vitest 4: globalSetup's default export should return the teardown function.
// Also re-exported as a named `teardown` for tooling that uses the old contract.
export default async function setup() {
  console.log('🚀 minikube-live global setup starting...\n');
  await ensureMinikube();
  await ensureImage(
    'kubeclaw-agent:latest',
    'container/Dockerfile',
    '.',
    // Verify tool-server.js is present — a stale image built from the
    // orchestrator Dockerfile will be missing this file and cause tool
    // pod jobs to fail with MODULE_NOT_FOUND at runtime.
    ['/app/dist/tool-server.js'],
    // Force rebuild when src/, container/, or root build files change.
    ['src', 'container', 'package.json', 'tsconfig.json'],
  );
  // The orchestrator image is also used by channel pods (different command).
  await ensureImage(
    'kubeclaw-orchestrator:latest',
    'Dockerfile',
    '.',
    [],
    ['src', 'package.json', 'tsconfig.json', 'Dockerfile'],
  );
  await ensureImage(
    'kubeclaw-test-mcp:latest',
    'e2e/fixtures/test-mcp-server/Dockerfile',
    'e2e/fixtures/test-mcp-server',
  );
  await ensureImage(
    'kubeclaw-test-embedding:latest',
    'e2e/fixtures/test-embedding-server/Dockerfile',
    'e2e/fixtures/test-embedding-server',
  );
  await ensureImage(
    'kubeclaw-test-ircd:latest',
    'e2e/fixtures/test-ircd/Dockerfile',
    'e2e/fixtures/test-ircd',
  );
  await ensureImage(
    'kubeclaw-test-oauth:latest',
    'e2e/fixtures/test-oauth-provider/Dockerfile',
    'e2e/fixtures/test-oauth-provider',
  );
  // Bootstrap Jobs and steady-state channel pods share the generic agent image
  // (kubeclaw-agent:latest). The image's channel-loader.js dispatches on
  // KUBECLAW_BOOTSTRAP_SKILL / presence of /runtime/channel-entry.js,
  // so no separate channel-base image is needed.

  try {
    await installCertManager();
  } catch (err) {
    console.warn(
      `⚠️  cert-manager install warning: ${err instanceof Error ? err.message : err}`,
    );
  }

  await helmInstall();

  console.log('⏳ Waiting for orchestrator pod Ready...');
  await waitForPod('app=kubeclaw-orchestrator', 240_000);
  console.log('⏳ Waiting for redis pod Ready...');
  await waitForPod('app=kubeclaw-redis', 180_000);
  console.log('⏳ Waiting for channel pod Ready...');
  await waitForPod('app=kubeclaw-channel-http', 240_000);
  console.log('⏳ Waiting for test embedding pod Ready...');
  await waitForPod('app=kubeclaw-capability-test-embed', 240_000);
  console.log('⏳ Waiting for test ircd pod Ready...');
  await waitForPod('app=kubeclaw-capability-test-ircd', 240_000);
  console.log('⏳ Waiting for test oauth provider pod Ready...');
  await waitForPod('app=kubeclaw-capability-test-oauth', 240_000);

  // The channel pod often loses its first Redis subscribe attempt — the
  // Redis pod's readiness probe goes True before the server is actually
  // accepting ACL'd connections, and ioredis bails after the default
  // maxRetriesPerRequest. Force a rollout restart so the channel pod's
  // subscribe runs against a fully-warm Redis.
  console.log('♻️  Restarting channel pod against warm Redis...');
  run('kubectl', [
    'rollout',
    'restart',
    'deployment/kubeclaw-channel-http',
    '-n',
    NAMESPACE,
  ]);
  // Wait briefly for the old pod's termination then for the new one to be Ready.
  await sleep(3000);
  await waitForPod('app=kubeclaw-channel-http', 240_000);
  // The test MCP capability is installed at runtime by the test itself,
  // so we don't wait for it here.

  await startPortForward();
  await startRedisPortForward();
  await startOauthWebchatPortForward();
  await startTestOauthPortForward();
  await startAdminPortForward();

  console.log('✅ minikube-live global setup complete\n');

  return teardownImpl;
}

export { teardownImpl as teardown };
