/**
 * e2e tests for Story 6: Sender allowlist drop mode.
 *
 * Acceptance criteria:
 *  1. mode:"drop" + allowlist → blocked sender POST → no SQLite row
 *  2. mode:"drop" + allowlist → allowed sender POST → stored
 *  3. Hot-reload (overwrite file, no restart) updates behavior
 *  4. mode:"trigger" still stores, just gates LLM dispatch
 *  5. kubectl logs shows "sender-allowlist: dropping message" for drops
 *     NOTE: AC5 cannot pass — the current channel-runner.ts onMessage handler
 *     drops silently (return without logging). The log "sender-allowlist: trigger
 *     denied for sender" only fires in isTriggerAllowed (trigger mode), not in
 *     the drop-mode path. AC5 is marked skipped with this note.
 *
 * Prerequisites:
 *  - kind cluster kubeclaw-e2e-istio (context: kind-kubeclaw-e2e-istio)
 *  - kubeclaw-orchestrator:e2e-test image loaded into kind
 *  - KUBECLAW_SKIP_HELM_INSTALL=true (prevent global-setup racing)
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { execSync, spawn } from 'child_process';
import type { ChildProcess } from 'child_process';

const NS = 'kubeclaw-e2e-allowlist';
const RELEASE = 'ke2e-allowlist';
const CONTEXT = 'kind-kubeclaw-e2e-istio';
const LOCAL_PORT = 14093;
const HTTP_PORT = 4080; // channel pod's httpPort

// DB path inside channel pod: /app/store/messages-http.db
const DB_PATH = '/app/store/messages-http.db';
// Allowlist path inside channel pod — resolved at runtime from $HOME inside the pod
// to handle different base images. Discovered in beforeAll and written here.
let ALLOWLIST_PATH = '/home/node/.config/kubeclaw/sender-allowlist.json';

// Helm install timeout (ms) — waiting for orchestrator + Redis + channel
const INSTALL_TIMEOUT = 300_000;
const TEST_TIMEOUT = 60_000;

let portForwardProc: ChildProcess | null = null;
let httpUsers = '';

function kube(args: string, opts?: { allowFail?: boolean }): string {
  try {
    return execSync(
      `kubectl --context ${CONTEXT} --namespace ${NS} ${args}`,
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] },
    ).trim();
  } catch (e: any) {
    if (opts?.allowFail) return (e.stdout ?? '').trim();
    throw e;
  }
}

function kubeGlobal(args: string, opts?: { allowFail?: boolean }): string {
  try {
    return execSync(`kubectl --context ${CONTEXT} ${args}`, {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
  } catch (e: any) {
    if (opts?.allowFail) return (e.stdout ?? '').trim();
    throw e;
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

/** Read the users line from the channel secret and extract credentials. */
function readChannelUsers(): { user: string; pass: string } {
  const usersB64 = kube(
    `get secret kubeclaw-channel-http -o jsonpath={.data.users}`,
  );
  httpUsers = Buffer.from(usersB64, 'base64').toString('utf8').trim();
  // Format: "admin:password" (single user generated by Helm)
  const colon = httpUsers.indexOf(':');
  if (colon === -1) throw new Error(`Unexpected users format: ${httpUsers}`);
  return { user: httpUsers.slice(0, colon), pass: httpUsers.slice(colon + 1) };
}

function basicAuth(user: string, pass: string): string {
  return 'Basic ' + Buffer.from(`${user}:${pass}`).toString('base64');
}

/** POST a message to the channel pod via the forwarded port. */
async function postMessage(
  user: string,
  pass: string,
  text: string,
): Promise<number> {
  const res = await fetch(`http://localhost:${LOCAL_PORT}/message`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: basicAuth(user, pass),
    },
    body: JSON.stringify({ text }),
  });
  return res.status;
}

/**
 * Count rows in the channel pod's SQLite DB matching a text fragment.
 *
 * The channel pod uses sql.js (WASM SQLite) and stores the DB at
 * /app/store/messages-http.db. sql.js saves as a standard SQLite binary, so
 * raw strings are stored verbatim in the page data. We grep the binary file
 * for the unique text fragment — this is reliable for short, unique strings
 * that will not appear in SQLite metadata.
 */
function countDbRows(textFragment: string): number {
  const podName = kube(
    `get pod -l app=kubeclaw-channel-http -o jsonpath={.items[0].metadata.name}`,
  );
  if (!podName) return -1;

  // grep -c exits 1 when there are 0 matches — use '|| echo 0' to normalize
  const result = kube(
    `exec ${podName} -- sh -c "test -f ${DB_PATH} && grep -c '${textFragment}' ${DB_PATH} || echo 0"`,
    { allowFail: true },
  );
  const n = parseInt(result.trim(), 10);
  return isNaN(n) ? 0 : n;
}

/**
 * Write the sender-allowlist file into the channel pod.
 *
 * Uses base64 encoding to safely transfer the JSON content without shell
 * quoting issues (JSON contains double quotes).
 */
function writeAllowlist(content: string): void {
  const podName = kube(
    `get pod -l app=kubeclaw-channel-http -o jsonpath={.items[0].metadata.name}`,
  );
  if (!podName) throw new Error('Channel pod not found');
  const b64 = Buffer.from(content, 'utf8').toString('base64');
  // Use base64 -d to decode into the file — avoids all quoting hazards
  kube(
    `exec ${podName} -- sh -c "mkdir -p $(dirname ${ALLOWLIST_PATH}) && echo ${b64} | base64 -d > ${ALLOWLIST_PATH}"`,
  );
}

/**
 * Remove the sender-allowlist file from the channel pod (resets to defaults).
 */
function removeAllowlist(): void {
  const podName = kube(
    `get pod -l app=kubeclaw-channel-http -o jsonpath={.items[0].metadata.name}`,
    { allowFail: true },
  );
  if (!podName) return;
  kube(`exec ${podName} -- rm -f ${ALLOWLIST_PATH}`, { allowFail: true });
}

/**
 * Wait until the port-forward is accepting connections.
 */
async function waitForPortForward(timeoutMs = 20_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`http://localhost:${LOCAL_PORT}/`, {
        signal: AbortSignal.timeout(2000),
        headers: { Authorization: basicAuth('probe', 'x') },
      });
      // Any response (including 401) means the port-forward is alive
      if (res.status > 0) return;
    } catch {
      // Not ready yet
    }
    await sleep(1000);
  }
  throw new Error(`Port-forward to localhost:${LOCAL_PORT} not ready after ${timeoutMs}ms`);
}

/** Wait for the channel pod to be ready (health endpoint returns 200). */
async function waitForChannelReady(timeoutMs = 120_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const pfOk = await fetch(`http://localhost:${LOCAL_PORT}/`, {
        signal: AbortSignal.timeout(2000),
        headers: { Authorization: basicAuth('probe', 'x') },
      });
      // 401 or 200 both mean the HTTP server is up
      if (pfOk.status > 0) return;
    } catch {
      // not ready
    }
    await sleep(2000);
  }
  throw new Error(`Channel not ready after ${timeoutMs}ms`);
}

// ── Skip guard: only run on the istio kind cluster ────────────────────────────

const clusterReachable = (() => {
  try {
    execSync(`kubectl --context ${CONTEXT} cluster-info`, {
      encoding: 'utf8',
      stdio: 'pipe',
    });
    return true;
  } catch {
    return false;
  }
})();

// ══════════════════════════════════════════════════════════════════════════════
// Test suite
// ══════════════════════════════════════════════════════════════════════════════

describe.skipIf(!clusterReachable)(
  'sender-allowlist drop mode (Story 6)',
  { timeout: INSTALL_TIMEOUT },
  () => {
    let adminUser = '';
    let adminPass = '';
    let installed = false;

    beforeAll(async () => {
      // Clean up any previous run
      execSync(
        `kubectl --context ${CONTEXT} delete namespace ${NS} --ignore-not-found --timeout=60s`,
        { stdio: 'pipe' },
      );
      // Wait for namespace termination
      for (let i = 0; i < 30; i++) {
        const nsExists = kubeGlobal(`get namespace ${NS} 2>/dev/null || echo NOTFOUND`, {
          allowFail: true,
        });
        if (nsExists.includes('NOTFOUND') || nsExists === '') break;
        await sleep(2000);
      }

      // Install kubeclaw with HTTP channel
      execSync(
        [
          `helm --kube-context ${CONTEXT} upgrade --install ${RELEASE} ./helm/kubeclaw`,
          `--namespace ${NS} --create-namespace`,
          `--set namespace=${NS}`,
          `--set image.tag=e2e-test`,
          `--set image.pullPolicy=IfNotPresent`,
          `--set credentialInjection.broker.image=kubeclaw-orchestrator:e2e-test`,
          `--set credentialInjection.mode=off`,
          `--set orchestrator.replicas=1`,
          `--set channels.http.enabled=true`,
          `--set channels.http.type=http`,
          `--set channels.http.httpPort=${HTTP_PORT}`,
          `--set "channels.http.envVars[0].name=HTTP_CHANNEL_USERS"`,
          `--set "channels.http.envVars[0].key=users"`,
          `--set "channels.http.envVars[1].name=HTTP_CHANNEL_PORT"`,
          `--set "channels.http.envVars[1].key=port"`,
          `--set "channels.http.envVars[1].optional=true"`,
          `--set secrets.httpChannelUsers=testuser:testpass`,
          `--set networkPolicy.enabled=false`,
        ].join(' '),
        { stdio: 'inherit', timeout: 120_000 },
      );
      installed = true;

      // Wait for orchestrator
      execSync(
        `kubectl --context ${CONTEXT} rollout status deployment/kubeclaw-orchestrator -n ${NS} --timeout=180s`,
        { stdio: 'inherit' },
      );

      // Wait for channel
      execSync(
        `kubectl --context ${CONTEXT} rollout status deployment/kubeclaw-channel-http -n ${NS} --timeout=180s`,
        { stdio: 'inherit' },
      );

      // Kill any stale process bound to the local port (port-forward or otherwise)
      execSync(`fuser -k ${LOCAL_PORT}/tcp 2>/dev/null || true`, { shell: true });
      await sleep(1000);

      // Start port-forward to channel pod directly
      const channelPodName = kube(
        `get pod -l app=kubeclaw-channel-http -o jsonpath={.items[0].metadata.name}`,
      );
      portForwardProc = spawn(
        'kubectl',
        [
          '--context', CONTEXT,
          '--namespace', NS,
          'port-forward',
          `pod/${channelPodName}`,
          `${LOCAL_PORT}:${HTTP_PORT}`,
        ],
        { stdio: 'ignore', detached: false },
      );

      await waitForPortForward(30_000);

      // Read generated credentials
      const creds = readChannelUsers();
      adminUser = creds.user;
      adminPass = creds.pass;

      // Wait for the channel HTTP server to be reachable (it may need a moment
      // after the port-forward is established)
      await waitForChannelReady(60_000);

      // Discover the actual HOME directory inside the channel pod so we write
      // the allowlist file to the right path regardless of base image.
      const podName = kube(
        `get pod -l app=kubeclaw-channel-http -o jsonpath={.items[0].metadata.name}`,
      );
      const homeDir = kube(`exec ${podName} -- sh -c 'echo $HOME'`);
      if (homeDir && homeDir !== '$HOME') {
        ALLOWLIST_PATH = `${homeDir}/.config/kubeclaw/sender-allowlist.json`;
      }
      console.log(`[allowlist-drop] HOME=${homeDir}, ALLOWLIST_PATH=${ALLOWLIST_PATH}`);

      // Remove any existing allowlist so we start clean
      removeAllowlist();
    }, INSTALL_TIMEOUT);

    afterAll(() => {
      if (portForwardProc) {
        portForwardProc.kill();
        portForwardProc = null;
      }
      if (installed) {
        execSync(
          `helm --kube-context ${CONTEXT} uninstall ${RELEASE} -n ${NS} 2>/dev/null || true`,
          { stdio: 'pipe' },
        );
        execSync(
          `kubectl --context ${CONTEXT} delete namespace ${NS} --wait=false 2>/dev/null || true`,
          { stdio: 'pipe' },
        );
      }
    }, 60_000);

    // ── AC1: drop mode + allowlist → blocked sender → no DB row ──────────────

    it(
      'AC1: blocked sender POST is not stored in SQLite (mode:drop)',
      async () => {
        const allowlistConfig = JSON.stringify({
          default: { allow: [adminUser], mode: 'drop' },
          chats: {},
          logDenied: true,
        });
        writeAllowlist(allowlistConfig);
        // Give the channel pod a moment to re-read the config (it reads on each message)
        await sleep(500);

        const uniqueText = `AC1-blocked-${Date.now()}`;

        // POST as a blocked sender (use a different user credential — but HTTP
        // auth is per-user, and the blocked sender is a different username).
        // We need a second user. Since we only have one user from secrets,
        // we test blocking by posting with a different "sender" identity.
        // The HTTP channel uses the authenticated username as sender.
        // The allowlist allows only adminUser; we need another user to be blocked.
        // Since the Helm chart generates one user, we'll manipulate the allowlist
        // to block the admin user itself by setting allow to a different name.
        const blockedAllowlist = JSON.stringify({
          default: { allow: ['nobody-allowed'], mode: 'drop' },
          chats: {},
          logDenied: true,
        });
        writeAllowlist(blockedAllowlist);
        await sleep(500);

        const status = await postMessage(adminUser, adminPass, uniqueText);
        expect(status).toBe(200);

        // Give channel pod time to process
        await sleep(1000);

        const count = countDbRows(uniqueText);
        expect(count, 'Blocked sender message must NOT appear in DB').toBe(0);
      },
      TEST_TIMEOUT,
    );

    // ── AC2: drop mode + allowlist → allowed sender → stored ─────────────────

    it(
      'AC2: allowed sender POST is stored in SQLite (mode:drop)',
      async () => {
        const allowlistConfig = JSON.stringify({
          default: { allow: [adminUser], mode: 'drop' },
          chats: {},
          logDenied: true,
        });
        writeAllowlist(allowlistConfig);
        await sleep(500);

        const uniqueText = `AC2-allowed-${Date.now()}`;
        const status = await postMessage(adminUser, adminPass, uniqueText);
        expect(status).toBe(200);

        await sleep(1500);

        const count = countDbRows(uniqueText);
        expect(count, 'Allowed sender message must be stored in DB').toBeGreaterThan(0);
      },
      TEST_TIMEOUT,
    );

    // ── AC3: hot-reload (overwrite file without restart) ─────────────────────

    it(
      'AC3: hot-reload — overwriting allowlist without restart changes behavior',
      async () => {
        // Phase 1: set mode:drop with nobody allowed → post → not stored
        const blockAll = JSON.stringify({
          default: { allow: ['nobody'], mode: 'drop' },
          chats: {},
          logDenied: true,
        });
        writeAllowlist(blockAll);
        await sleep(500);

        const blockedText = `AC3-blocked-${Date.now()}`;
        await postMessage(adminUser, adminPass, blockedText);
        await sleep(1000);
        expect(countDbRows(blockedText), 'Phase 1: blocked sender not stored').toBe(0);

        // Phase 2: overwrite allowlist to allow adminUser → post → stored
        const allowAdmin = JSON.stringify({
          default: { allow: [adminUser], mode: 'drop' },
          chats: {},
          logDenied: true,
        });
        writeAllowlist(allowAdmin);
        // No pod restart — the channel-runner reads the file on each message
        await sleep(500);

        const allowedText = `AC3-allowed-${Date.now()}`;
        await postMessage(adminUser, adminPass, allowedText);
        await sleep(1500);
        expect(
          countDbRows(allowedText),
          'Phase 2: allowed sender stored after hot-reload',
        ).toBeGreaterThan(0);
      },
      TEST_TIMEOUT,
    );

    // ── AC4: mode:trigger still stores (just gates LLM dispatch) ─────────────

    it(
      'AC4: mode:trigger stores message even for non-triggering sender',
      async () => {
        // In trigger mode, blocked senders' messages are still stored in DB;
        // they just don't trigger LLM dispatch.
        const triggerConfig = JSON.stringify({
          default: { allow: ['nobody'], mode: 'trigger' },
          chats: {},
          logDenied: true,
        });
        writeAllowlist(triggerConfig);
        await sleep(500);

        const uniqueText = `AC4-trigger-${Date.now()}`;
        const status = await postMessage(adminUser, adminPass, uniqueText);
        expect(status).toBe(200);

        await sleep(1500);

        // In trigger mode the message IS stored (allowlist only gates dispatch)
        const count = countDbRows(uniqueText);
        expect(
          count,
          'mode:trigger must store message regardless of allowlist',
        ).toBeGreaterThan(0);
      },
      TEST_TIMEOUT,
    );

    // ── AC5: log line for drops ──

    it(
      'AC5: kubectl logs shows "sender-allowlist: dropping message" for drops',
      async () => {
        writeAllowlist(
          JSON.stringify({
            default: { allow: ['nobody-allowed'], mode: 'drop' },
            chats: {},
            logDenied: true,
          }),
        );
        await sleep(500);
        const uniqueText = `AC5-drop-${Date.now()}`;
        await postMessage(adminUser, adminPass, uniqueText);
        await sleep(2000);
        const logs = execSync(
          `kubectl --context ${CONTEXT} logs -n ${NS} deployment/kubeclaw-channel-http --tail=400`,
          { encoding: 'utf8' },
        );
        expect(logs).toMatch(/sender-allowlist: dropping message/);
      },
      TEST_TIMEOUT,
    );
  },
);
